version: '3'

services:
  websocket-stt-chat:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASSEMBLYAI_API_KEY=523d85f64d974fc0a84bdb53c8a8615d
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 